### ISSUE TITLE
what other spacer/standoffs sizes are compatible

### ISSUE THREAD

**Issue by logicalbhanu** [keyzog/kapl#7]
Hi,
My issue is i am not getting m2 spacer nearby and nor on online at least in my country at good price, can i use m3 spacer or m2.5 spacer, or what are the other options regarding sizes for spacers if possible?

**Comment by keyzog** [comment]
Hi!
The size of the hole in the board to accommodate the standoffs is 3.5mm. Only M2 of a standoffs will fit into such a hole.

![Снимок экрана 2023-09-20 224737](https://github.com/keyzog/kapl/assets/7888825/cbbe920b-e055-4e6d-89e6-90e9750187cc) ![611UOvakShL _AC_UF350,350_QL80_](https://github.com/keyzog/kapl/assets/7888825/d6e1a763-e108-44b8-bbf8-59a6a86d620a)

You can save money by using regular M2 bolts and nuts. Just calculate the height of the bolts so that they are not too long. This method is not as convenient and aesthetically pleasing compared to standsoffs.

You can also use spacers made of different materials. For example, print on a 3D printer or wrap some [duct tape))](https://live.staticflickr.com/8160/7214525854_733237dd83_z.jpg)

![kek2](https://github.com/keyzog/kapl/assets/7888825/48a3e3eb-47f9-4946-aaf3-edddb2dea304)

Be careful, the very first version of the board had 3.2mm holes; if you ordered the board more than a year ago, you may have this version.

**Comment by logicalbhanu** [comment]
i eventually get the m2 spacer/standoff so order it, 

but here i am with a new issue and that is, i am try to test the working of some keys before soldering all of them, thus i perform the following tasks:
1. solder all the diodes.
2. flash the pro micros with kapl_v1.hex file given in the link of the repo( i do test my pro connecting two of its pins on opposite sides and they are printing something on my device terminal app).
3. fit all the keys to the top plate and set it with pcb.
4. solder one key among all the keys to test whether it is working or not.

but sadly i am not getting any character when pressing that key, i also tried the reset button and that also seems to be not working( what i am doing is, why reflashing my pro micro rather than shorting the GND and RST pins i am pressing the reset button in the hope that it will start the flash in the qmk toolbox app like it did if shorted the pins directly but nothing is happening there).

i don't know what i am doing wrong so here is the picture of my setup 

<img width="582" alt="image" src="https://github.com/keyzog/kapl/assets/40262328/c879b18b-a77e-4864-9ae5-2aa90ccad1f9">

the circled key is the one i have souldered to test the pcb(i order the pcb for jlpcb so i am expecting it of good quality).
so once again can you guide toward any pointer which can help me figure out.

**Comment by keyzog** [comment]
![image](https://github.com/keyzog/kapl/assets/7888825/14c2c120-fb36-492d-8eda-bc13134367a3)

1) This pin look bad soldered. If the contact is poor, the switches will operate very unstable.
2) You missed one diode.
3) Did you remember to solder the diode under the controller?

![image](https://github.com/keyzog/kapl/assets/7888825/322f77db-04a1-4bdf-9b8b-44099602184c)

For just testing pcb you can use tweeters. This is not very convenient, but it is much easier than soldering each switch for testing. https://www.youtube.com/shorts/-FCV9InV3x8

It’s better to write to me in telegram or email, it will be more productive. Contacts are in the profile.

**Comment by logicalbhanu** [comment]
thanks again, yes i soldered the diode(it is not visible though because of the pro micro), but yes i do missed the second diode that you pointed out(thanks again), and also thanks for the telegram info it will be much helpfull for me.
